version: 2

sources:
  - name: stg_airport
    schema: stg
    description: Source schema containing airport data
    tables:
      - name: airports_data
        description: >
          Source table containing internal airport data including names in multiple languages,
          geographic coordinates, and update timestamps.
        columns:
          - name: airport_code
            description: Unique airport code
          - name: airport_name
            description: containing names in multiple languages
          - name: city
            description: containing city names in multiple languages
          - name: coordinates
            description: Point data representing geographic location
          - name: timezone
            description: Timezone of the airport
          - name: last_update
            description: Timestamp when the record was last updated