version: 2

sources:
  - name: stg_airport
    schema: stg
    tables:
      - name: airports_data
      - name: aircrafts_data
      - name: seats


models:
    - name: dim_airport
      description: "airports data table"
      columns:
        - name: airport_code
          description: "Unique IATA airport code"
          data_test:
            - unique
            - not_null
    - name: dim_aircraft
      description: "aircrafts data table"
      columns:
        - name: aircraft_code
          description: "Unique aircraft code"
          data_test:
            - unique
            - not_null