version: 2
models:
  - name: fact_flights
    description: "Fact table containing flight information"
    columns:
      - name: flight_id
        description: "Unique identifier"
        data_test:
         - name: not_null
         - name: unique

sources:
  - name: stg
    schema: stg
    tables:
    - name: airports_data
      identifier: airports_data
    - name: flights
    - name: seats
    - name: boarding_passes
    - name: ticket_flights
    - name: tickets